version: '3.8'

services:
  web:
    build: .
    depends_on:
      - db
    volumes:
      - .:/app
    ports:
      - 8000:8000
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=fastapi
    expose:
      - 5432

volumes:
    postgres_data:
